// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dejuxheqsswqumjdgipi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlanV4aGVxc3N3cXVtamRnaXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDYzNzMsImV4cCI6MjA2OTkyMjM3M30.mHRn0zg0uoct-aKQAhXGx93WhjP0dq5H5mBUIGP1DNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});